version: "3.0"
services:
  app:
    container_name: bank-connect-app
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - pqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pqldb:5000/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  pqldb:
    image: postgres
    ports:
      - "5000:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_connect
    volumes:
      - bank-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  bank-data:
